# Copyright (C) 2011-2018 Project SkyFire <http://www.projectskyfire.org/>
#

version: '1.0.{build}-{branch}'

# Build worker image (VM template)
image: 
 - Visual Studio 2013
 - MySQL 5.7

environment:
  matrix: 
  - SF_VERSION: TBC
    VS_VER: Visual Studio 12 2013
  - SF_VERSION: TBC
    VS_VER: Visual Studio 12 2013 Win64
  #- SF_VERSION: Cata
  #  VS_VER: Visual Studio 12 2013
  #- SF_VERSION: Cata
  #  VS_VER: Visual Studio 12 2013 Win64
  #- SF_VERSION: Panda
  #  VS_VER: Visual Studio 12 2013
  #- SF_VERSION: Panda
  #  VS_VER: Visual Studio 12 2013 Win64
  #- SF_VERSION: Legion
  #  VS_VER: Visual Studio 12 2013
  #- SF_VERSION: Legion
  #  VS_VER: Visual Studio 12 2013 Win64
  
# build Configuration, i.e. Debug, Release, etc.
configuration:
  #- Debug
  - Release

# scripts that are called, before repo cloning  
init:
  - cmd: git config --global core.autocrlf input
  - cmd: cmake --version
  - cmd: msbuild /version  

# Clone to the specified folder below, and only clone the latest commit without history.
#clone_folder: C:\Projects\SkyFireONE
#clone_depth: 1

# scripts that run after cloning repository
#install:
#  - cmd: cd C:\Projects\SkyFireONE
#  - cmd: git submodule update --init

# scripts to run before build  
before_build:
  - cmd: echo %VS_VER%
  - cmd: echo %Configuration%  

# Build core.  
build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake ../ -G "%VS_VER%" -DBUILD_WITH_WARNINGS=0 -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DBUILD_TOOLS=0 -DBUILD_SCRIPTS=1 -DSF_VERSION=%SF_VERSION%
  - cmd: msbuild SkyFireONE.sln

  # enable MSBuild parallel builds
  - max_jobs: 2
  - parallel: true

  # MSBuild verbosity level (quiet|minimal|normal|detailed)
  - verbosity: normal
  